export default function practitionerData() {
  return {
      scrolled: false,
      accountMenuOpen: false,
      profileDialogOpen: false,
      currentTimestamp: Date.now(),
      statsAnimationProgress: 0,
      statsAnimationFrameId: null,
      statsAnimationStarted: false,
      statsSectionVisible: false,
      menuClockTimer: null,
      publicAutoRefreshTimer: null,
      loginDialogOpen: false,
      isRegistrationOpen: false,
      publicSnapshot: null,
      publicStats: null,
      loginRedirectPath: '',
      loginForm: {
        loginCode: '',
        password: '',
      },
      navItems: [
        { href: '#about', label: 'عن البرنامج' },
        { href: '#competencies', label: 'مجالات وكفايات البرنامج' },
        { href: '#requirements', label: 'المتطلبات' },
      ],
      licensePrograms: [
        {
          key: 'licenses',
          title: 'الرخص المهنية',
          menuSubtitle: '',
          available: true,
          route: { name: 'home', hash: '#programs' },
          icon: 'mdi-view-grid-outline',
        },
        {
          key: 'manager',
          title: 'رخصة مدير',
          menuSubtitle: '',
          available: false,
          route: null,
          icon: 'mdi-briefcase-outline',
        },
        {
          key: 'supervisor',
          title: 'رخصة مشرف',
          menuSubtitle: '',
          available: false,
          route: null,
          icon: 'mdi-eye-outline',
        },
        {
          key: 'secretary',
          title: 'رخصة سكرتير',
          menuSubtitle: '',
          available: false,
          route: null,
          icon: 'mdi-clipboard-text-outline',
        },
      ],
      goals: [
        'التعرّف على أهمية العلم الشرعي وأهم مسائل العقيدة والطهارة والصلاة',
        'إتقان أساسيات تعليم القرآن الكريم ومبادئ علم التجويد',
        'توظيف الأساليب التربوية المناسبة في التعامل مع الطلاب',
        'استحضار أهمية الرسالة التعليمية والالتزام بها',
        'تطبيق مهارات التواصل والتخطيط في البيئة التعليمية',
        'إدارة الحلقة القرآنية وتنظيمها بكفاءة',
      ],
      domains: [
        {
          title: 'كفايات المجال الشرعي',
          icon: 'mdi-book-open-page-variant',
          items: [
            'أهمية العلم الشرعي وأثره في حياة المعلم/ة',
            'أهم مسائل التوحيد والإيمان',
            'أهم مسائل الطهارة',
            'الأحكام العامة للصلاة',
          ],
        },
        {
          title: 'كفايات المجال التعليمي',
          icon: 'mdi-school-outline',
          items: [
            'مبادئ أحكام التجويد نظريًا وتطبيقيًا',
            'استراتيجيات تعليم القرآن الكريم',
            'مباحث وآداب قرآنية',
          ],
        },
        {
          title: 'كفايات المجال التربوي',
          icon: 'mdi-hand-heart-outline',
          items: [
            'مدخل في التربية وأهميتها وخصائصها',
            'خصائص المراحل العمرية واحتياجاتها',
            'الأساليب التربوية',
            'بناء القيم وتعزيز السلوك',
            'الصحة النفسية في البيئة التعليمية',
          ],
        },
        {
          title: 'كفايات المجال المهاري',
          icon: 'mdi-star-four-points-outline',
          items: [
            'مهارات التواصل الفعال',
            'إدارة الحلقة القرآنية',
            'تكامل شخصية المعلم',
            'مهارات التخطيط',
            'التعامل مع النظام التقني (ناظم)',
            'الدور الاستراتيجي للمعلم والمعلمة',
          ],
        },
      ],
      includesItems: [
        { num: '01', title: 'لقاءات تدريبية حضورية', icon: 'mdi-school' },
        { num: '02', title: 'مهام أدائية تطبيقية', icon: 'mdi-clipboard-check-outline' },
        { num: '03', title: 'عرض القرآن', icon: 'mdi-book-open-blank-variant' },
        { num: '04', title: 'اختبارات قبلية وبعدية', icon: 'mdi-file-document-check-outline' },
        { num: '05', title: 'اختبار نهائي', icon: 'mdi-trophy-outline' },
      ],
      requirements: [
        { text: 'حضور ما لا يقل عن (10) لقاءات من اللقاءات التدريبية', icon: 'mdi-calendar-check-outline' },
        { text: 'تنفيذ (80%) من المهام الأدائية', icon: 'mdi-clipboard-check-multiple-outline' },
        { text: 'اجتياز الاختبار النهائي بنسبة لا تقل عن (70%)', icon: 'mdi-text-box-check-outline' },
        { text: 'الالتزام بآداب وأخلاقيات تعليم القرآن الكريم', icon: 'mdi-heart-outline' },
      ],
      recitation: [
        { tag: 'الرجال', text: 'المعلمون: عرض كامل القرآن', icon: 'mdi-book-open-page-variant-outline' },
        { tag: 'النساء', text: 'المعلمات: عرض (10) أجزاء', icon: 'mdi-book-open-page-variant-outline' },
      ],
      durationQuickInfo: [
        { label: 'المدة', value: 'ستة أسابيع', icon: 'mdi-clock-outline' },
        { label: 'التكرار', value: 'دورتان أسبوعيًا', icon: 'mdi-calendar-week' },
        { label: 'آلية التنفيذ', value: 'حضوريًا', icon: 'mdi-map-marker-outline' },
      ],
      startDates: [
        { tag: 'الرجال', text: 'يوم الإثنين 18 / 10 / 1447هـ' },
        { tag: 'النساء', text: 'يوم السبت 23 / 10 / 1447هـ' },
      ],
    };
}
