export const LICENSE_PROGRAM_META = [
  {
    key: 'manager',
    status: 'قريباً',
    available: false,
    route: null,
    icon: 'mdi-briefcase-outline',
    cardColor: '#08384a',
    cardColorLight: '#e8f6fb',
    poster: true,
    posterVars: {
      '--poster-title': '#07385f',
      '--poster-text': '#1d3f5d',
      '--poster-line-start': '#1d75b9',
      '--poster-line-end': '#6bb7e8',
      '--poster-circle-start': '#eaf5fb',
      '--poster-circle-end': '#f8fbfd',
      '--poster-platform-start': '#eef8fb',
      '--poster-platform-end': '#d9eef5',
      '--poster-platform-shadow': 'rgba(20, 95, 145, 0.13)',
      '--poster-platform-after': '#eef4f7',
      '--poster-leaf-start': '#7ec4d9',
      '--poster-leaf-end': '#2b8dbd',
      '--poster-document-shadow': 'rgba(9, 55, 95, 0.14)',
      '--poster-doc-line': '#b8dce7',
      '--poster-accent': '#0e7da7',
      '--poster-dot': '#8ac6d8',
      '--poster-feature-shadow': 'rgba(11, 47, 74, 0.08)',
      '--poster-feature-shadow-hover': 'rgba(11, 47, 74, 0.12)',
      '--poster-icon-bg-start': '#eef8fb',
      '--poster-icon-bg-end': '#d9eef5',
      '--poster-icon-border': '#d6e8ef',
      '--poster-feature-text': '#123a58',
    },
  },
  {
    key: 'practitioner',
    status: 'متاحة الآن',
    available: true,
    route: { name: 'practitioner' },
    icon: 'mdi-certificate-outline',
    cardColor: '#08384a',
    cardColorLight: '#e8f6fb',
    poster: true,
    posterVars: {
      '--poster-title': '#145a37',
      '--poster-text': '#2c5a45',
      '--poster-line-start': '#1f8f57',
      '--poster-line-end': '#7fd8a9',
      '--poster-circle-start': '#e7f7ef',
      '--poster-circle-end': '#f7fcf9',
      '--poster-platform-start': '#eefaf4',
      '--poster-platform-end': '#d9f1e3',
      '--poster-platform-shadow': 'rgba(31, 143, 87, 0.12)',
      '--poster-platform-after': '#eef6f1',
      '--poster-leaf-start': '#8fd6b2',
      '--poster-leaf-end': '#1f8f57',
      '--poster-document-shadow': 'rgba(20, 90, 55, 0.14)',
      '--poster-doc-line': '#c7e7d3',
      '--poster-accent': '#1f8f57',
      '--poster-dot': '#8fd6b2',
      '--poster-feature-shadow': 'rgba(20, 90, 55, 0.08)',
      '--poster-feature-shadow-hover': 'rgba(20, 90, 55, 0.12)',
      '--poster-icon-bg-start': '#eefaf4',
      '--poster-icon-bg-end': '#d9f1e3',
      '--poster-icon-border': '#d3eadb',
      '--poster-feature-text': '#214838',
    },
  },
  {
    key: 'supervisor',
    status: 'قريباً',
    available: false,
    route: null,
    icon: 'mdi-eye-outline',
    cardColor: '#08384a',
    cardColorLight: '#e8f6fb',
    poster: true,
    posterVars: {
      '--poster-title': '#8a5a00',
      '--poster-text': '#5d471c',
      '--poster-line-start': '#d99a13',
      '--poster-line-end': '#ffd66b',
      '--poster-circle-start': '#fff4d8',
      '--poster-circle-end': '#fffdf7',
      '--poster-platform-start': '#fff8e6',
      '--poster-platform-end': '#f7e4ad',
      '--poster-platform-shadow': 'rgba(217, 154, 19, 0.12)',
      '--poster-platform-after': '#fbf5e8',
      '--poster-leaf-start': '#ffd66b',
      '--poster-leaf-end': '#d99a13',
      '--poster-document-shadow': 'rgba(117, 82, 18, 0.14)',
      '--poster-doc-line': '#f1dca7',
      '--poster-accent': '#d99a13',
      '--poster-dot': '#ffd66b',
      '--poster-feature-shadow': 'rgba(117, 82, 18, 0.08)',
      '--poster-feature-shadow-hover': 'rgba(117, 82, 18, 0.12)',
      '--poster-icon-bg-start': '#fff8e6',
      '--poster-icon-bg-end': '#f7e4ad',
      '--poster-icon-border': '#ecd79d',
      '--poster-feature-text': '#4c3a14',
    },
  },
  {
    key: 'secretary',
    status: 'قريباً',
    available: false,
    route: null,
    icon: 'mdi-clipboard-text-outline',
    cardColor: '#08384a',
    cardColorLight: '#e8f6fb',
    poster: true,
    posterVars: {
      '--poster-title': '#0f6f77',
      '--poster-text': '#25545a',
      '--poster-line-start': '#12a8b4',
      '--poster-line-end': '#74dce4',
      '--poster-circle-start': '#e7fbfc',
      '--poster-circle-end': '#fbffff',
      '--poster-platform-start': '#eefcfd',
      '--poster-platform-end': '#d8f4f6',
      '--poster-platform-shadow': 'rgba(18, 168, 180, 0.12)',
      '--poster-platform-after': '#eef8f8',
      '--poster-leaf-start': '#74dce4',
      '--poster-leaf-end': '#12a8b4',
      '--poster-document-shadow': 'rgba(18, 108, 115, 0.14)',
      '--poster-doc-line': '#c8edf0',
      '--poster-accent': '#12a8b4',
      '--poster-dot': '#74dce4',
      '--poster-feature-shadow': 'rgba(18, 108, 115, 0.08)',
      '--poster-feature-shadow-hover': 'rgba(18, 108, 115, 0.12)',
      '--poster-icon-bg-start': '#eefcfd',
      '--poster-icon-bg-end': '#d8f4f6',
      '--poster-icon-border': '#cfeaec',
      '--poster-feature-text': '#244f55',
    },
  },
];

export const PROGRAM_CONTENT_INDEX_BY_KEY = {
  practitioner: 0,
  manager: 1,
  supervisor: 2,
  secretary: 3,
};
