<template>
  <div class="people-page">
    <output
      v-if="dialogDataLoading"
      class="d-block"
    >
      جارٍ تحميل بيانات النافذة…
    </output>
    <PeopleDirectoryPanel
      :error="directoryError || dashboardError || dialogDataError"
      :loading="directoryLoading"
      :search="directorySearch"
      :page="directoryPage"
      :page-count="directoryPages"
      :total="directoryTotal"
      :managed-branch-id="managedBranchId"
      :branch="selectedBranch"
      :branch-options="branchFilterOptions"
      :filter="selectedFilter"
      :filter-options="filterOptions"
      :can-create="canCreateAny"
      :people="visiblePeopleCards"
      :reciter-mode="isReciterDirectoryMode"
      :selected-student-id="selectedStudentId"
      :can-edit="canEditVisiblePeople"
      :can-delete="canDeleteVisiblePeople"
      :can-edit-student="canEditStudent"
      :can-assign-reciter="canAssignReciter"
      :organization-label="organizationLabel"
      @update:branch="selectedBranch = $event"
      @update:filter="selectedFilter = $event"
      @search="searchDirectory"
      @page="loadPeopleDirectory"
      @retry="loadPeopleDirectory()"
      @branch-change="handleBranchFilterChange"
      @create="openCreateDialog"
      @select="selectStudent"
      @edit="openEditDialogFor($event.type, $event.id)"
      @delete="openDeletePersonDialog"
      @assign-reciter="openReciterAssignmentDialog"
      @metric="handleMetricClick($event.person, $event.key)"
    />

    <PeopleManagementDialogs
      :parts-open="partsDialogOpen"
      :parts="partsRange"
      :parts-student-id="partsDialogStudentId"
      :saving-part-key="partsDialogSavingKey"
      :can-manage-parts="canManageStudentParts"
      :is-part-completed="isCompletedDialogPart"
      :delete-open="deleteDialogOpen"
      :delete-type-label="deleteTargetTypeLabel"
      :delete-name="deleteTargetName"
      :delete-submitting="deleteDialogSubmitting"
      :reciter-open="reciterDialogOpen"
      :reciter-id="reciterDialogReciterId"
      :reciter-label="reciters.find((person) => person.id === reciterDialogReciterId)?.name || 'غير مرتبط'"
      :reciter-branch="reciterDialogStudent?.branchId || effectiveStudentBranch"
      :allow-unassign="canEditReciter"
      :reciter-options="reciterAssignmentOptions"
      :reciter-saving="reciterDialogSaving || dialogDataLoading"
      :manage-open="manageDialogOpen"
      :manage-entity-type="manageEntityType"
      :entity-options="availableEntityOptions"
      :manage-branch-id="manageBranchId"
      :branch-options="branchOptions"
      :direct-card-edit="isDirectCardEdit"
      :manage-target-label="manageTargetLabel"
      :manage-target-id="manageTargetId"
      :manage-target-options="manageTargetOptions"
      :select-menu-props="manageSelectMenuProps"
      :can-manage-selected="canManageSelectedEntity"
      :manage-submitting="manageDialogSubmitting || dialogDataLoading"
      @parts-toggle="handlePartsDialogToggle"
      @parts-close="closePartsDialog"
      @part-toggle="toggleDialogPart"
      @delete-toggle="handleDeleteDialogToggle"
      @delete-confirm="confirmDeletePerson"
      @delete-close="closeDeleteDialog"
      @reciter-toggle="handleReciterDialogToggle"
      @update:reciter-id="selectReciterTarget"
      @reciter-close="closeReciterDialog"
      @reciter-submit="submitReciterAssignment"
      @manage-toggle="handleManageDialogToggle"
      @update:manage-entity-type="manageEntityType = $event"
      @update:manage-branch-id="manageBranchId = $event"
      @update:manage-target-id="selectManageTarget"
      @manage-context-change="handleManageContextChange"
      @manage-edit="openEditFromManageDialog"
      @manage-delete="submitManageDeleteWithSuccessFallback"
      @manage-close="closeManageDialog"
    />

    <PeopleEditorDialog
      ref="peopleEditorDialog"
      :value="dialogOpen"
      :file-picker-open="bulkFilePickerOpen"
      :title="dialogTitle"
      :editing="isEditing"
      :direct-card-edit="isDirectCardEdit"
      :entity-type="dialogEntityType"
      :can-add-student="canAddStudent"
      :bulk-importing="bulkImporting"
      :entity-options="availableEntityOptions"
      :branch-id="dialogBranchId"
      :branch-options="branchOptions"
      :target-id="editingTargetId"
      :target-options="editTargetOptions"
      :target-label="dialogTargetLabel"
      :name-label="dialogNameLabel"
      :name-placeholder="dialogNamePlaceholder"
      :name="activeName"
      :linked-students="linkedStudentOptions"
      :linked-student-ids="reciterForm.studentIds"
      :login-code="activeLoginCode"
      :password="activePassword"
      :password-confirmation="activePasswordConfirmation"
      :password-requirements="PASSWORD_REQUIREMENTS_TEXT"
      :registration-rows="registrationProfileRows((editingStudentRecord || {}).registrationProfile)"
      :errors="dialogErrors"
      :submitting="dialogSubmitting || dialogDataLoading"
      @input="handleDialogToggle"
      @update:entity-type="dialogEntityType = $event"
      @update:branch-id="dialogBranchId = $event"
      @update:target-id="editingTargetId = $event"
      @update:name="activeName = $event"
      @update:login-code="activeLoginCode = $event"
      @update:password="activePassword = $event"
      @update:password-confirmation="activePasswordConfirmation = $event"
      @context-change="handleDialogContextChange"
      @target-change="handleEditingTargetChange"
      @toggle-student="toggleLinkedStudent"
      @open-file-picker="openBulkFilePicker"
      @file-change="handleBulkFileChange"
      @submit="submitDialog"
      @close="closeDialog"
    />
  </div>
</template>

<script src="../features/people/adminPeopleView.js"></script>

<style src="../styles/views/admin-people.css"></style>
<style src="../styles/views/admin-people-dialogs.css"></style>
